//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace insanKaynaklari.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Worker
    {
        public int ID { get; set; }
        public int Salary { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> BusinessId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public int RoleId { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Department Department { get; set; }
        public virtual Person Person { get; set; }
        public virtual UserRole UserRole { get; set; }
    }
}
